### ISSUE TITLE
mutate example does not work

### ISSUE THREAD

**Issue by 89z** [w-henderson/Humphrey#101]
From here:

https://humphrey.whenderson.dev/json/untyped-values.html#manipulating-json-values

~~~rust
use humphrey_json::Value;

fn main() {
   let data = r#"
   {"age": 43, "name": "John Doe"}
   "#;
   let value: Value = humphrey_json::from_str(data).unwrap();
   // expected enum `Value`, found `&str`
   value["name"] = "Humphrey";
   dbg!(value);
}
~~~

**Comment by w-henderson** [comment]
This was simply a mistake on my part - the new value to set must be a `Value`. I've fixed this and the documentation should update shortly.

**Comment by 89z** [comment]
OK cool - thank you!

**Comment by 89z** [comment]
confirmed fixed, thanks!
