### ISSUE TITLE
as_string

### ISSUE THREAD

**Issue by 89z** [w-henderson/Humphrey#104]
I think it would be helpful to have an as_string, method, similar to as_str:

<https://docs.rs/humphrey_json/latest/humphrey_json/value/enum.Value.html#method.as_str>

In fact, it would be simpler than the current method:

https://github.com/w-henderson/Humphrey/blob/017fe240359bcc2e6972c4aa5abe9d3b28add6d0/humphrey-json/src/value.rs#L88-L93

as you could drop the extra method call:

~~~rust
use humphrey_json::Value;

pub fn as_string(&self) -> Option<String> {
   if let Value::String(s) = self {
      Some(s)
   } else {
      None
   }
}
~~~

Currently I am doing something like this:

~~~rust
use humphrey_json::Value;

pub fn as_string(v: Value) -> Option<String> {
   v.as_str().map(str::to_string)
}
~~~

**Comment by w-henderson** [comment]
One more thing - please bear in mind that unless you need to mutate the string, you don't need an owned `String` and therefore don't need the clone!

**Comment by 89z** [comment]
I am new to Rust, so honestly I dont know how to do what youre suggesting. If I try this:

~~~rust
pub fn hello(v: humphrey_json::Value) -> Option<&str> {
   v["hello"].as_str()
}
~~~

I get this:

~~~
1 | pub fn hello(v: humphrey_json::Value) -> Option<&str> {
  |                                                 ^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
  |
1 | pub fn hello(v: humphrey_json::Value) -> Option<&'static str> {
  |                                                  +++++++
~~~

If I try this:

~~~rust
pub fn hello(v: humphrey_json::Value) -> Option<&'static str> {
   v["hello"].as_str()
}
~~~

I get this:

~~~
2 |    v["hello"].as_str()
  |    -^^^^^^^^^^^^^^^^^^
  |    |
  |    returns a value referencing data owned by the current function
  |    `v` is borrowed here
~~~

**Comment by 89z** [comment]
OK I am dumb, I think I got my crates mixed up. The suggestion in the output is misleading, you can just borrow the input:

~~~rust
use humphrey_json::Value;

pub fn hello(v: &Value) -> Option<&str> {
   v["hello"].as_str()
}
~~~

**Comment by w-henderson** [comment]
This is correct - you can't return a reference to data owned by the function. When taking the argument by value, you cannot return a reference to the value, since it is dropped when the function returns.
