### ISSUE TITLE
Missing features that prevent actual use

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [w-henderson/Humphrey#116]
Hello,

I am looking for a simple http server that does not require a full async runtime. 
This is suprisingly hard to come by, as all other http server implementation introduce extreme amounts of complexity 
trying to solve the c10k problem. A problem which I do not have.
The base design choices you have made fits my bill perfectly, 
however there are a few essential missing features that prevent actual use.

Disclaimer: I have not looked at your "tokio" implementation or any of your http client code as that part of your project does not intrest me.

1. You load every Request body/Response body must be represented as a Vec u8.
=> Unfortunately that rules out any chance of the server ever receiving a large file that an endpoint would like to stream into a file for example. 
=> The way you implement this makes the server trivial to DDOS. (I do not have this concern as any application I am currently considering to write using your library will probably be either in a DMZ or in an air gapped network) 
=> I need to send and receive data in the 5-50GB range per request, which is not feasible with your current implementation

2. You do not implement chunked transfer encoding.
=> This makes streaming data nearly impossible. There are many use cases where an endpoint either as input (Request Body) or output (Response Body) will begin streaming or generating data from somewhere having no knowledge on how big the payload will end up being.
Sure, the endpoint could gather everything before sending. This is however not practical as this introduces slowdown. For my use case generation of data that should be sent may take a very long time and id appreciate already being able to send data while I still work on 
assembling the data. (The client on the other end can and will already begin working on crunching the partially received data)

3. There is no concept of filters for either requests or responses.
=> Consider an application that has many endpoints. If an application requires proprietary non standard authentication then this is not possible to implement without massive pain given your current architecture. Given a Web-Server like
Jetty for Java for example one would install a request filter that processes the request objects before deciding if the request should go to routing or not. The filter would probably access the request headers (maybe the query parameters...) then do some proprietary magic before either aborting the request then and there with a fully populated response object or let the request proceed to routing.
With your architecture the first call of every endpoint would be a call to some "is_authenticated" function. This is needlessly painful.

=> For responses the same thing applies. A common use case is to attach custom headers to responses that should apply to all
or well a large amount of responses. Again doing so in every endpoint method is pain-full and very prone to errors as this is easily forgotten.

4. Your implementation of CORS makes a fair amount of other use cases impossible.
=> As far as I can see your code will hijack any Options requests. There are many other use cases where endpoints need to be able
to customize the exact response that the Options request would have to return. I understand the reasoning why you did it this way,
but normally such things (CORS) would be handled in a filter and thus be placed in the responsability of the user of the library.
That way special circumstances that require carefully crafted responses to Options requests can be done.

5. There is no way to get rid of Server, Date and a bunch of other headers you hard code into every response.
=> This is not desired for some use cases, consider giving us a boolean flag to turn this behavior off.

Filters could probably be added without breaking changes to the api, but everything else would probably require breaking changes. Especially the Vec u8  -> "something" like Box dyn Read change would probably be a massive breaking change that cannot be hidden.

I would be willing to work on all theses topics and submit pull requests, however I have seen that a large pull request has been largely ignored for months now so before I waste my time I would like to ask if you first of all even desire the changes I am proposing after considering my reasoning for them. Second do you still have interest in maintaining this project because you mentioned in the other large pull request that you have to focus on your studies (which is fair).

Sincerely
Alexander Schütz

**Comment by w-henderson** [comment]
Thanks you for taking such a thorough look at my project! While these are all totally reasonable changes to make, I'm afraid that I'm too busy in my final year of university to properly maintain this project at the moment. Maybe when I graduate I might take another look at it, but knowing what I know now it would probably be better to take a weekend and start again from scratch - you're absolutely right in that some of my design decisions don't make any sense!

**Comment by Grinkers** [comment]
@AlexanderSchuetz97 I think our use cases are very similar (or at least a lot of overlap). I don't care about c10k, async, tls, etc. I do care about low latency (so 1 thread per connection is perfect). I use Humphrey in a DMZ. It's been a low priority for me, but I was considering forking (or maybe starting over with a subset of goals). It seems like you were willing to do work, but even more eyes/feedback could be very useful.

If you're interested in swapping ideas, you can grab my email from the commits from https://github.com/w-henderson/Humphrey/pull/114. I'm also on discord by the same name. I don't think this issue is the place to discuss things.

@w-henderson good luck with school! Thank you for your work on this project. It really highlighted a missing library in the rust ecosystem.
